[package]
name = "sap-cranelift"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Cranelift backend for sap expressions"

[dependencies]
sap-core.workspace = true
