[package]
name = "rhizome-dew-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core expression language for dew"

[features]
default = []
cond = []
func = []

[dependencies]

[dev-dependencies]
proptest = "1.5"
